version: '3.8'

services:
  # Node.js application service
  app:
    build: ./restaurant-management-system  # Path to the Node.js application
    ports:
      - "3000:3000"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
    networks:
      - app_network

  # RabbitMQ service
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ default messaging port
      - "15672:15672"  # RabbitMQ Management Console port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persistent data storage
      - ./rabbitmq_plugins:/plugins  # Mount for custom plugins
    command: >
      sh -c "
      rabbitmq-plugins enable rabbitmq_management &&
      rabbitmq-plugins enable rabbitmq_delayed_message_exchange &&
      rabbitmq-server"
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge

volumes:
  rabbitmq_data:
